/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.blade.hooklib;

import java.lang.annotation.*;

@Target(ElementType.METHOD)
@Retention(RetentionPolicy.CLASS)
public @interface BladeImport {

}
