/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.blade.hooklib;

import java.lang.annotation.*;

@Target(ElementType.TYPE)
@Retention(RetentionPolicy.CLASS)
public @interface BladeInject {
    String name();
}
